System:
    Default:
        Economy:
            #
            # Round reward amounts to the nearest integer
            # Default : false
            IntegerCurrency: false

        Hunting: 
            #
            # Give rewards for mob spawner camping
            # Default: false
            AllowCamping: false
            #
            # Clear drops from mobs killed from spawners
            # Default: true
            ClearCampDrops: true
            #
            # How many blocks away from a spawner you need to be to get a reward
            # Default: 7            
            CampRadius: 7
            #
            # Replace instead of stack custom mob drops
            # Default: true
            OverrideDrops: true
            #
            # Do not randomize the amount of custom drop items - always drop a fixed amount
            # Default: false
            FixedDrops: false
            #
            # Enable rewards for mobs killed with bow & arrow
            # Default: true
            BowRewards: true
            #
            # Enable rewards for killing mobs under sea level
            # Default: true
            AllowUnderSeaLVL: true
            #
            # Enable rewards for kills with tamed creatures (wolves)
            # Default: true
            WolverineMode: true
            #
            # Penalize players when they die. Use PenalizeType to select whether PenalizeAmount
            # is used as a percentage (PenalizeType: true) or a fixed amount (PenalizeType: false)
            # Default: false
            PenalizeDeath: false
            # Default: true
            PenalizeType: true
            # Default: 0.05
            PenalizeAmount: 0.05
            #
            # Reward players for player kills. Use PVPRewardType to select whether PVPRewardAmount
            # is used as a percentage (PVPRewardType: true) or a fixed amount (PVPRewardType: false)
            # Default: true
            PVPReward: true
            # Default: true
            PVPRewardType: true
            # Default: 0.05
            PVPRewardAmount: 0.05
            #
            # Remove drops from mobs killed by farming contraptions (mob death by cacti, falling,
            # drowning or suffocation)
            # Default: false
            NoFarm: false

        Messages:
            #
            # Enable/disable all reward messages
            # Default: true
            Output: true
            #
            # Message players when they get no reward for a kill
            # Default: true
            NoReward: true
            #
            # Message players when they destroy a mob spawner
            # Default: false
            Spawner: false
            #
            # Custom message for no camping mob spawners
            NoCampMessage: '&7You find no rewards camping monster spawners.'
            #
            # Custom message for no rewards killing with bow & arrow
            NoBowMessage: '&7You find no rewards on this creature.'
            #
            # Custom message for death penalty
            DeathPenaltyMessage: '&7You wake up to find &6<amt>&7 missing from your pockets!'
            #
            # Custom message for PVP reward
            PVPRewardMessage: '&7You are awarded &6<amt>&7 for murdering &5<crt>.'

    #
    # Override any or all of the default settings on a per world basis. Any settings not specified
    # will use the above defaults.
    # 
    example_world1:
        #
        # This example overrides the death penalty amount to be fixed at 10 in this world
        Hunting:
            PenalizeDeath: true
            PenalizeType: false
            PenalizeAmount: 10
        Messages:
            DeathPenaltyMessage: '&7Dying in this world will cost you &6<amt>&7!'

    example_world2:
        #
        # This example disables rewards for PVP in this world
        Hunting:
            PVPReward: false

Gain:
    Default:
        #
        # Multiply reward amount based on group (IMPORTANT NOTE: requires a permission plugin that
        # supports groups)
        Groups:
            Default:
                Amount: 1.0
            Donors:
                Amount: 2.0
        #
        # Multiply reward amount based on time period of day/night
        Time:
            Sunrise:
                Amount: 1.0
            Day:
                Amount: 1.0
            Sunset:
                Amount: 1.0
            Dusk:
                Amount: 1.125
            Night:
                Amount: 1.25
            Dawn:
                Amount: 1.125
        #
        # Multiply reward amount based on environment type
        Environment:
            Normal: 1.0
            Nether: 1.0
            Skylands: 1.0
    #
    # Override any or all of the default settings on a per world basis. Any settings not specified
    # will use the above defaults.
    # 
    example_world1:
    	#
    	# This example overrides Night multiplier from the default 1.25 to 2.0 in this world
        Time:
        	Night:
        		Amount: 2.0

    example_world2:
    	#
    	# This example overrides the Environment multiplier for Nether in this world
    	Environment:
    		Nether: 2.0

RewardTable:
    Default:
        CaveSpider:
            Drops: '287:2:75'
            Coin_Minimum: 0.50
            Coin_Maximum: 1.50
            Coin_Percent: 50.0
        Chicken:
            Drops: '288:2:75;365:1:75'
            Coin_Minimum: 0.10
            Coin_Maximum: 2.00
            Coin_Percent: 1.0
        Cow:
            Drops: '334:2:75;363:3:75'
            Coin_Minimum: 0.10
            Coin_Maximum: 2.50
            Coin_Percent: 1.0
        Creeper:
            Drops: '289:2:75'
            Coin_Minimum: 5.50
            Coin_Maximum: 10.50
            Coin_Percent: 50.0
        Enderman:
            Drops: '368:1:75'
            Coin_Minimum: 1.00
            Coin_Maximum: 3.50
            Coin_Percent: 50.0
        Ghast:
            Drops: '289:2:75'
            Coin_Minimum: 3.50
            Coin_Maximum: 3.50
            Coin_Percent: 50.0
        Giant:
            Coin_Minimum: 8.50
            Coin_Maximum: 8.50
            Coin_Percent: 50.00
        Monster:
            Coin_Minimum: 0.50
            Coin_Maximum: 1.50
            Coin_Percent: 50.0
        Pig:
            Drops: '319:2:75'
            Coin_Minimum: 0.10
            Coin_Maximum: 2.50
            Coin_Percent: 1.0
        PigZombie:
            Drops: '320:2:75'
            Coin_Minimum: 1.00
            Coin_Maximum: 3.50
            Coin_Percent: 50.0
        Sheep:
            Drops: '35:1:75'
            Coin_Minimum: 0.10
            Coin_Maximum: 2.50
            Coin_Percent: 1.0
        Silverfish:
            Coin_Minimum: 0.50
            Coin_Maximum: 0.50
            Coin_Percent: 50.0
        Skeleton:
            Drops: '352:2:75;262:2:75'
            Coin_Minimum: 1.00
            Coin_Maximum: 3.00
            Coin_Percent: 50.0
        Slime:
            Drops: '341:2:75'
            Coin_Minimum: 0.00
            Coin_Maximum: 2.00
            Coin_Percent: 50.00
        Spider:
            Drops: '287:2:75'
            Coin_Minimum: 0.50
            Coin_Maximum: 1.50
            Coin_Percent: 50.0
        Squid:
            Drops: '351:3:75'
            Coin_Minimum: 0.10
            Coin_Maximum: 2.50
            Coin_Percent: 1.0
        Wolf:
            Coin_Minimum: 1.00
            Coin_Maximum: 2.00
            Coin_Percent: 1.0
        Zombie:
            Drops: '367:2:75'
            Coin_Minimum: 1.00
            Coin_Maximum: 3.50
            Coin_Percent: 50.0
        Spawner:
            Coin_Minimum: 0.10
            Coin_Maximum: 15.00
            Coin_Percent: 50.0
            NoReward_Message: '&7You destroyed a &5<crt>&7 using a &3<itm>.'
            Reward_Message: '&7You are awarded &6<amt>&7 for destroying a &5<crt>.'
            Penalty_Message: '&7You are penalized &6<amt>&7 for destroying a &5<crt>.'
    #
    # Override any or all of the default settings on a per world basis. Any settings not specified
    # will use the above defaults.
    # 
    example_world1:
    	#
    	# This example overrides the default reward message for Enderman in this world
        Enderman:
	        Reward_Message: '&7Nice job! Here's &6<amt>&7 for kill an &5<crt>.'
    		
    example_world2:
    	#
    	# This example overrides the default drops for
    	PigZombie:
    		Drops: ''