System:
    Economy:
        #
        # Round reward amounts to the nearest integer
        # Default : false
        IntegerCurrency: false

    Hunting:
        #
        # Give rewards for mob spawner camping
        # Default: false
        AllowCamping: false
        #
        # Clear drops from mobs killed from spawners
        # Default: true
        ClearCampDrops: true
        #
        # How many blocks away from a spawner you need to be to get a reward
        # Default: 7            
        CampRadius: 7
        #
        # Replace instead of stack custom mob drops
        # Default: true
        OverrideDrops: true
        #
        # Do not randomize the amount of custom drop items - always drop a fixed amount
        # Default: false
        FixedDrops: false
        #
        # Enable rewards for mobs killed with bow & arrow
        # Default: true
        BowRewards: true
        #
        # Enable rewards for killing mobs under sea level
        # Default: true
        AllowUnderSeaLVL: true
        #
        # Enable rewards for kills with tamed creatures (wolves)
        # Default: true
        WolverineMode: true
        #
        # Penalize players when they die. Use PenalizeType to select whether PenalizeAmount
        # is used as a percentage (PenalizeType: true) or a fixed amount (PenalizeType: false)
        # taken from the player
        # Default: false
        PenalizeDeath: false
        # Default: true
        PenalizeType: true
        # Default: 0.05
        PenalizeAmount: 0.05
        #
        # Reward players for player kills. Use PVPRewardType to select whether PVPRewardAmount
        # is used as a percentage (PVPRewardType: true) or a fixed amount (PVPRewardType: false)
        # taken from the victim
        # Default: true
        PVPReward: true
        # Default: true
        PVPRewardType: true
        # Default: 0.05
        PVPRewardAmount: 0.05
        #
        # DeathTpPlus - reward players for kill/death streaks. Use DTPRewardAmount for fixed reward amount
        # IMPORTANT NOTE: requires "classic" build of plugin here http://tiny.cc/dtpclassic
        # Default: true (false if DeathTpPlus plugin is not detected)
        DTPRewards: true
        DTPDeathStreakPenalty: 0.0
        DTPKillStreakReward: 10.0
        #
        # Remove drops from mobs killed by farming contraptions (mob death by cacti, falling,
        # drowning or suffocation)
        # Default: false
        NoFarm: false

    Messages:
        #
        # Enable/disable all reward messages
        # Default: true
        Output: true
        #
        # Message players when they get no reward for a kill
        # Default: true
        NoReward: true
        #
        # Message players when they destroy a mob spawner
        # Default: false
        Spawner: false
        #
        # Custom message for no camping mob spawners
        NoCampMessage: '&7You find no rewards camping monster spawners.'
        #
        # Custom message for no rewards killing with bow & arrow
        NoBowMessage: '&7You find no rewards on this creature.'
        #
        # Custom message for death penalty
        DeathPenaltyMessage: '&7You wake up to find &6<amt>&7 missing from your pockets!'
        #
        # Custom message for PVP reward
        PVPRewardMessage: '&7You are awarded &6<amt>&7 for murdering &5<crt>.'
        #
        # Custom message for DTP penalty
        DTPDeathStreakMessage: '&7That death streak cost you &6<amt>&7.'
        #
        # Custom message for DTP reward
        DTPKillStreakMessage: '&7You are awarded &6<amt>&7 for that kill streak!'

Gain:
    #
    # Multiply reward amount based on group (IMPORTANT NOTE: requires a permission plugin that
    # supports groups)
    Groups:
        Default:
            Amount: 1.0
        Donors:
            Amount: 2.0
    #
    # Multiply reward amount based on time period of day/night
    Time:
        Sunrise:
            Amount: 1.0
        Day:
            Amount: 1.0
        Sunset:
            Amount: 1.0
        Dusk:
            Amount: 1.125
        Night:
            Amount: 1.25
        Dawn:
            Amount: 1.125
    #
    # Multiply reward amount based on environment type
    Environment:
        Normal:
            Amount: 1.0
        Nether:
            Amount: 1.0
        Skylands:
            Amount: 1.0

RewardTable:
    #
    # Format for Drops:
    #
    #   ITEM_ID.DATA_ID:[MIN-]MAX:CHANCE;ITEM_ID.DATA_ID:[MIN-]MAX:CHANCE;...
    #
    # Example 1: 'diamond:5:50'
    #   Drops 0 to 5 diamonds 50% of the time
    #
    # Example 2: 'leaves.2:1-2:100'
    #   Drops 1 to 2 birch leaves 100% of the time
    #
    # Example 3: 'diamond:5:50;leaves.2:1-2:100'
    #   Drops 0 to 5 diamonds 50% of the time AND drops 1 to 2 birch leaves 100% of the time
    #
    # Example 4: ''
    #   Drop nothing
    #
    # Coin reward examples:
    #
    # Example 1: award 0 to 10 coin 50% of the time
    #   Coin_Minimum: 0.0 
    #   Coin_Maximum: 10.0
    #   Coin_percent: 50.0
    #
    # Example 2: award 10 coin 100% of the time
    #   Coin_Minimum: 10.0 
    #   Coin_Maximum: 10.0
    #   Coin_percent: 50.0
    #
    # Example 3: award nothing
    #
    #   Coin_Minimum: 0.0 
    #   Coin_Maximum: 0.0
    #   Coin_percent: 0.0
    #
    CaveSpider:
        Drops: 'string:2:75'
        Coin_Minimum: 0.50
        Coin_Maximum: 1.50
        Coin_Percent: 50.0
    Chicken:
        Drops: 'feather:2:75;365:1:75'
        Coin_Minimum: 0.10
        Coin_Maximum: 2.00
        Coin_Percent: 1.0
    Cow:
        Drops: 'leather:2:75;rawbeef:3:75'
        Coin_Minimum: 0.10
        Coin_Maximum: 2.50
        Coin_Percent: 1.0
    Creeper:
        Drops: 'sulphur:2:75'
        Coin_Minimum: 5.50
        Coin_Maximum: 10.50
        Coin_Percent: 50.0
    Enderman:
        Drops: 'enderpearl:1:75'
        Coin_Minimum: 1.00
        Coin_Maximum: 3.50
        Coin_Percent: 50.0
    Ghast:
        Drops: 'sulphur:2:75'
        Coin_Minimum: 3.50
        Coin_Maximum: 3.50
        Coin_Percent: 50.0
    Giant:
        Coin_Minimum: 8.50
        Coin_Maximum: 8.50
        Coin_Percent: 50.00
    Monster:
        Coin_Minimum: 0.50
        Coin_Maximum: 1.50
        Coin_Percent: 50.0
    Pig:
        Drops: 'pork:2:75'
        Coin_Minimum: 0.10
        Coin_Maximum: 2.50
        Coin_Percent: 1.0
    PigZombie:
        Drops: 'grilledpork:2:75'
        Coin_Minimum: 1.00
        Coin_Maximum: 3.50
        Coin_Percent: 50.0
    Sheep:
        Drops: 'wool:1:75'
        Coin_Minimum: 0.10
        Coin_Maximum: 2.50
        Coin_Percent: 1.0
    Silverfish:
        Coin_Minimum: 0.50
        Coin_Maximum: 0.50
        Coin_Percent: 50.0
    Skeleton:
        Drops: 'bone:2:75;arrow:2:75'
        Coin_Minimum: 1.00
        Coin_Maximum: 3.00
        Coin_Percent: 50.0
    Slime:
        Drops: 'slimeball:2:75'
        Coin_Minimum: 0.00
        Coin_Maximum: 2.00
        Coin_Percent: 50.00
    Spider:
        Drops: 'string:2:75'
        Coin_Minimum: 0.50
        Coin_Maximum: 1.50
        Coin_Percent: 50.0
    Squid:
        Drops: 'inksack:3:75'
        Coin_Minimum: 0.10
        Coin_Maximum: 2.50
        Coin_Percent: 1.0
    Wolf:
        Coin_Minimum: 1.00
        Coin_Maximum: 2.00
        Coin_Percent: 1.0
    Zombie:
        Drops: 'rottenflesh:2:75'
        Coin_Minimum: 1.00
        Coin_Maximum: 3.50
        Coin_Percent: 50.0
    Spawner:
        Drops: ''
        Coin_Minimum: 0.10
        Coin_Maximum: 15.00
        Coin_Percent: 50.0
        NoReward_Message: '&7You destroyed a &5<crt>&7 using a &3<itm>.'
        Reward_Message: '&7You are awarded &6<amt>&7 for destroying a &5<crt>.'
        Penalty_Message: '&7You are penalized &6<amt>&7 for destroying a &5<crt>.'
