name: ecoCreature
main: se.crafted.chrisb.ecoCreature.ecoCreature
version: 0.0.8 (All your death are belong to us!)
depend: [Vault]
softdepend: [DeathTpPlus]
softdepend: [MobArena]
description: Coins and drops for PvM
permissions:
    ecocreature.gain.*:
        description: Allows all gain multipliers
        children:
            ecocreature.gain.group: true
            ecocreature.gain.time: true
            ecocreature.gain.environment: true
    ecocreature.reward.*:
        description: Allows rewards for all creature types
        children:
            ecocreature.reward.angrywolf: true
            ecocreature.reward.cavespider: true
            ecocreature.reward.chicken: true
            ecocreature.reward.cow: true
            ecocreature.reward.creeper: true
            ecocreature.reward.deathpenalty: true
            ecocreature.reward.deathstreak: true
            ecocreature.reward.enderman: true
            ecocreature.reward.ghast: true
            ecocreature.reward.giant: true
            ecocreature.reward.killstreak: true
            ecocreature.reward.monster: true
            ecocreature.reward.pig: true
            ecocreature.reward.pigzombie: true
            ecocreature.reward.player: true
            ecocreature.reward.poweredcreeper: true
            ecocreature.reward.sheep: true
            ecocreature.reward.silverfish: true
            ecocreature.reward.skeleton: true
            ecocreature.reward.slime: true
            ecocreature.reward.spawner: true
            ecocreature.reward.spider: true
            ecocreature.reward.squid: true
            ecocreature.reward.wolf: true
            ecocreature.reward.zombie: true
    ecocreature.gain.group:
        description: Enables gain multiplier based on group
        default: true
    ecocreature.gain.time:
        description: Enables gain multiplier based on time period
        default: true
    ecocreature.gain.environment:
        description: Enables gain multiplier based on environment
        default: true
    ecocreature.reward.angrywolf:
        description: Enables rewards for angry wolves
        default: true
    ecocreature.reward.cavespider:
        description: Enables rewards for cave spiders
        default: true
    ecocreature.reward.chicken:
        description: Enables rewards for chickens
        default: true
    ecocreature.reward.cow:
        description: Enables rewards for cows
        default: true
    ecocreature.reward.creeper:
        description: Enables rewards for creepers
        default: true
    ecocreature.reward.deathpenalty:
        description: Enables penalty for playe death
        default: true
    ecocreature.reward.deathstreak:
        description: Enables penalty for death streaks via DeathTpPlus
        default: true
    ecocreature.reward.enderman:
        description: Enables rewards for endermen
        default: true
    ecocreature.reward.ghast:
        description: Enables rewards for ghasts
        default: true
    ecocreature.reward.giant:
        description: Enables rewards for giants
        default: true
    ecocreature.reward.killstreak:
        description: Enables rewards for kill streaks via DeathTpPlus
        default: true
    ecocreature.reward.monster:
        description: Enables rewards for monsters
        default: true
    ecocreature.reward.pig:
        description: Enables rewards for pigs
        default: true
    ecocreature.reward.pigzombie:
        description: Enables rewards for zombies
        default: true
    ecocreature.reward.player:
        description: Enables rewards for players (a.k.a. PVP reward)
        default: true
    ecocreature.reward.poweredcreeper:
        description: Enables rewards for powered creepers
        default: true
    ecocreature.reward.sheep:
        description: Enables rewards for sheep
        default: true
    ecocreature.reward.silverfish:
        description: Enables rewards for silverfish
        default: true
    ecocreature.reward.skeleton:
        description: Enables rewards for skeletons
        default: true
    ecocreature.reward.slime:
        description: Enables rewards for slime
        default: true
    ecocreature.reward.spawner:
        description: Enables rewards for spawners
        default: true
    ecocreature.reward.spider:
        description: Enables rewards for spiders
        default: true
    ecocreature.reward.squid:
        description: Enables rewards for squid
        default: true
    ecocreature.reward.wolf:
        description: Enables rewards for wolves
        default: true
    ecocreature.reward.zombie:
        description: Enables rewards for zombies
        default: true
